DROP DATABASE IF EXISTS GuessTheNumberDatabase;
CREATE DATABASE GuessTheNumberDatabase;
USE GuessTheNumberDatabase;

CREATE TABLE Game (
	GameId INT PRIMARY KEY AUTO_INCREMENT,
	Answer INT NOT NULL,
	GameInProgress BOOLEAN
);

CREATE TABLE Guess (
	guessId INT PRIMARY KEY AUTO_INCREMENT,
	`Time` DATETIME NOT NULL,
	Answer INT NOT NULL,
	Result VARCHAR(30),
	GameId INT NOT NULL,
	CONSTRAINT fk_Guess_Game FOREIGN KEY (GameId)
		REFERENCES Game(GameId)
)